#active ' , 'more, split,e.g huawei,htc
active: huawei
devices:
    huawei:
        platformName: Android
        deviceName: emulator-5556
        platformVersion: 7.1
        autoAcceptAlerts: true
        unicodeKeyboard: true
        resetKeyboard: true
        #noReset: true
        fullReset: true
        # appPackage: com.android.browser
        # appActivity: .BrowserActivity
        appPackage: cn.com.walmart.mobile
        appActivity: .welcome.WelcomeActivity
        clearSystemFiles: true
        #app: '/Users/eric/Downloads/android.apk'
        url: 'http://192.168.21.30:4725/wd/hub'

    htc:
        platformName: Android
        deviceName: Android Emulator
        platformVersion: 4.3
        autoAcceptAlerts: true
        unicodeKeyboard: true
        resetKeyboard: true
        #appPackage = com.android.browser
        #appActivity = .BrowserActivity
        app: /Users/ddxflqm/ownCloud/TIMMY/android.apk
        url: 'http://192.168.21.58:4723/wd/hub'



